version: "3.9"

services:
  beget-bot:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: beget_bot

    restart: unless-stopped

    env_file:
      - .env

    volumes:
      - ./DATA:/app/DATA
      - ./files:/app/files
      - ./images:/app/images

    command: python main.py
