services:
  beget-bot:
    build: .
    container_name: beget_bot
    restart: unless-stopped

    environment:
      BOT_TOKEN: ${BOT_TOKEN}

    volumes:
      - ./DATA:/app/DATA
      - ./files:/app/files
      - ./images:/app/images

    command: python main.py
